name: Build PortAudio lib
on:
  push:
    branches-ignore:
      - master
permissions:
  # This is needed for pushing a new commit to the repo:
  contents: write
jobs:

  windows:
    runs-on: windows-2022
    strategy:
      matrix:
        platform: [x64, Win32]
        asio: ["", "-asio"]
        include:
          - platform: x64
            platform-suffix: 64bit
          - platform: Win32
            platform-suffix: 32bit
    env:
      # Reproducible build by avoiding time stamp
      LDFLAGS: "/Brepro"
    steps:
      - name: checkout portaudio
        uses: actions/checkout@v4
        with:
          repository: PortAudio/portaudio
          ref: master
          path: portaudio
      # The next portaudio release will have an auto-download feature:
      - name: download and extract ASIO SDK
        if: matrix.asio
        run: |
          curl -L -o asiosdk.zip https://www.steinberg.net/asiosdk
          7z x asiosdk.zip
      - name: cmake configure
        run: |
          cmake -S portaudio -B build -A ${{ matrix.platform }} -D PA_USE_ASIO=${{ matrix.asio && 'ON' || 'OFF' }}
      - name: cmake build
        run: |
          cmake --build build --config Release
      - name: rename DLL
        run: |
          mv build/Release/portaudio_*.dll libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.dll
          mv build/Release/portaudio_*.lib libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.lib
      - name: show some information about DLL
        run: |
          ldd libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.dll
          file libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.lib
      - name: upload DLL
        uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.platform }}-dll${{ matrix.asio }}
          path: libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.dll
      - uses: actions/upload-artifact@v4
        with:
          name: windows-${{ matrix.platform }}-lib${{ matrix.asio }}
          path: libportaudio${{ matrix.platform-suffix }}${{ matrix.asio }}.lib

  push:
    runs-on: ubuntu-latest
    needs: [windows]
    steps:
      - name: Clone Git repository
        uses: actions/checkout@v4
      - name: Retrieve x64 DLL
        uses: actions/download-artifact@v4
        with:
          name: windows-x64-dll
      - name: Retrieve x64 LIB
        uses: actions/download-artifact@v4
        with:
          name: windows-x64-lib
      - name: Retrieve x64 DLL with ASIO support
        uses: actions/download-artifact@v4
        with:
          name: windows-x64-dll-asio
      - name: Retrieve Win32 DLL
        uses: actions/download-artifact@v4
        with:
          name: windows-Win32-dll
      - name: Retrieve Win32 LIB
        uses: actions/download-artifact@v4
        with:
          name: windows-Win32-lib
      - name: Retrieve Win32 DLL with ASIO support
        uses: actions/download-artifact@v4
        with:
          name: windows-Win32-dll-asio
      - name: Commit and push binaries (if there are changes)
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git commit -am "Update binaries" && git push || true
